

services:
  app:
    build: .
    container_name: bot_container
    env_file:
      - .env
    volumes:
      - .:/usr/src/bot
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
